[package]
name = "turbe"
version = "0.1.0"
edition = "2024"

[package.metadata.turbo]
user = "63c55578-a270-42a9-9084-c89191a53418"

[dependencies]
turbo = { version = "5.2.1", package = "turbo-genesis-sdk" }

[lib]
crate-type = ["cdylib"]

[lints.rust]
unexpected_cfgs = { level = "allow" }
